#!/bin/bash

# this won't work if you haven't built the container image first
#   (run this script from the Dockerfile folder if you haven't: build_docker_crawlweb_image)

debug=${debug:-false}
pretend=${pretend:-false}
clean=${clean:-false}
command=${command:-}

if [ "$pretend" == true ]; then
  echo "Pretend mode on, not executing commands."
  prefix=echo 
else
  unset prefix
fi

if [ "$clean" == true ]; then
  echo "destroying old data..."
  $prefix docker volume rm crawlweb 
  $prefix docker volume rm crawldebug 
fi

if [ ! "$(docker volume ls -q | grep ^crawlweb$)" -o "$pretend" == true ]; then
  echo "creating docker volume..."
  $prefix docker volume create crawlweb 
fi

common_parameters="--rm -v crawlweb:/var/crawl -p 80:80 -p 8081:8081 --name crawlweb ufetubus/crawlweb"
if [ "$debug" == true ]; then
  echo "starting debug container..."
  $prefix docker run -it "$@" -v crawldebug:/usr/www $common_parameters $command
else
  echo "starting normal container..."
  $prefix docker run -d "$@" $common_parameters $command
fi

echo "done."

