#!/bin/bash

# this won't work if you haven't built the container image first
#   (run this script from the Dockerfile folder if you haven't: build_docker_crawlweb_image)

debug=true
if [ "$1" = clean ]; then
  echo "destroying old data..."
  docker volume rm crawlweb &>/dev/null
fi

if [ ! "$(docker volume ls -q | grep ^crawlweb$)" ]; then
  echo "creating docker volume..."
  docker volume create crawlweb >/dev/null
fi

common_parameters="--rm -v crawlweb:/var/crawl -p 80:80 -p 8081:8081 --name crawlweb ufetubus/crawlweb"
if [ "$debug" == true ]; then
  echo "starting debug container..."
  docker run -it $common_parameters
else
  echo "starting normal container..."
  docker run -d $common_parameters
fi

echo "done."

